// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindCareWeb.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MindCareWeb.Migrations
{
    [DbContext(typeof(MindCareDbContext))]
    [Migration("20251112150159_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MindCareWeb.Models.HistoricoMood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Humor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HISTORICO_MOOD", (string)null);
                });

            modelBuilder.Entity("MindCareWeb.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<int?>("IdUsuarioCriador")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeTarefa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("Id");

                    b.ToTable("TAREFA", (string)null);
                });

            modelBuilder.Entity("MindCareWeb.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("MindCareWeb.Models.UsuarioTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conquista")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ProgressoPercentual")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TarefaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("USUARIO_TAREFA", (string)null);
                });

            modelBuilder.Entity("MindCareWeb.Models.HistoricoMood", b =>
                {
                    b.HasOne("MindCareWeb.Models.Usuario", "Usuario")
                        .WithMany("Historicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindCareWeb.Models.UsuarioTarefa", b =>
                {
                    b.HasOne("MindCareWeb.Models.Tarefa", "Tarefa")
                        .WithMany()
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindCareWeb.Models.Usuario", "Usuario")
                        .WithMany("UsuarioTarefas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindCareWeb.Models.Usuario", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("UsuarioTarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
